version: '3.3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005

  db:
    image: mariadb:10.2.12
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      - MYSQL_HOST=db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      #- ./leajs.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
volumes:
  db_data: